---
# Changes here will be overwritten by Copier
_commit: b2b7279
_src_path: git@github.com:datarobot/af-component-base.git
copyright_year: 2025
github_owner_group: '@datarobot/buzok'
harness_org_id: buzok
include_core: true
oss_repo_name: agentic-writer
private_repo_name: recipe-datarobot-agent-application
template_code_name: agentic-writer
template_description: This application is a template for Generative AI agentic solutions
template_name: Agentic Writer
