---
# .taskfile-data.yaml
# Optional configuration for dr task compose

# Development server ports
# Displayed when running the dev task
ports:
  - name: Backend
    port: 8080
  - name: Frontend
    port: 5173
  - name: Agent
    port: 8842
  - name: MCP Server
    port: 9000
